### PR TITLE
Use pipenv

### LINKED ISSUE #334: Move hydrus to using Pipenv
### Why?
This helps with managing the dependent python version for hydrus to also be backward compatible. 
- Also the Pipfile.lock exercises caution with the use of SHA hashes to maintain integrity of dependencies. 
- Pipenv also provides a shell with auto-loading features to load env. variables, which might come in handy in the future.

### How?
- loading pipenv to install from requirements.txt, then deleting requirements.txt once Pipfiles generated.
- Locking Pipfile once version of Python set to 3.5.2.

### Do you want to work on this issue?
yes

### PR DESCRIPTION
**Pull request by de-sh**
Fixes #334 

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Description

This request is to move the hydrus code-base to using Pipenv as is pointed out in my comment on #303 and #334 . This helps with the integrity of all dependencies from PIP.

**ALL TESTS ARE PASSING**
```
Creating a temporary database...
going for create doc
Classes and properties added successfully.
Setting up Hydrus utilities... 
Creating utilities context... 
Setup done, running tests...
..../demoapi/anotherSingleClass
{'@context': '/demoapi/contexts/anotherSingleClass.jsonld', '@id': '/demoapi/', '@type': 'anotherSingleClass', 'Prop1': 'SEE90C'}
/demoapi/singleClass
{'@context': '/demoapi/contexts/singleClass.jsonld', '@id': '/demoapi/', '@type': 'singleClass', 'Prop1': 'NN5XE2', 'Prop2': 'W3DLRZ', 'dummyProp': '/demoapi/DcTest/2bc678b8-d75b-43a8-88f9-471a09f2692f', 'singleClassProp': '/demoapi/anotherSingleClass/'}
.............Creating a temporary datatbase...
Classes, Properties and Users added successfully.
Setting up Hydrus utilities... 
Creating utilities context... 
Setup done, running tests...
..........Creating a temporary datatbsse...
['User', 'Pet']
Pet
Classes and properties added successfully.
Setup done, running tests...
.........SELECT EXISTS (SELECT * 
FROM instances 
WHERE instances.id = ?) AS anon_1
.......Importing Open Api Documentation ..
......Method on path /pet/findByStatus already present !
Method on path /pet/findByTags already present !
Method on path /pet/{petId} already present !
Cannot parse path /pet/{petId} because no ref to local class provided
Cannot parse path /pet/{petId} because no ref to local class provided
Cannot parse path /store/inventory because no ref to local class provided
Cannot parse path /store/order/{orderId} because no ref to local class provided
Method on path /user/createWithArray already present !
Method on path /user/createWithList already present !
Cannot parse path /user/login because no ref to local class provided
Cannot parse path /user/logout because no ref to local class provided
Cannot parse path /user/{username} because no ref to local class provided
.../home/devdutt/Projects/HTTP-APIs/hydrus/hydrus
.
----------------------------------------------------------------------
Ran 53 tests in 2.603s

OK
```

### Change logs
Added use of Pipenv to manage Python version and dependencies, deleted requirements.txt, updated README file.

#### Changed

- Deleted requirements.txt
- Updated README.md to mirror change in setup process

#### Removed

- requirements.txt file for PIP dependency version management.

### CODE REVIEW

**Comment by de-sh** [comment]
Oh god, how does one change the head from HTTP-APIs:master to HTTP-APIs:develop after making a PR? :man_facepalming:

**Comment by de-sh** [comment]
The above issue can be solved by updating the CI. Else it is all perfectly fine on my computer :+1:

**Comment by Mec-iS** [comment]
I don't know if `pipenv` is the way to go yet. I know some situations in which it is impossible to solve version conflicts among libraries (one case is `boto3`). It is a great tool and in the future will be a standard practice but it seems that the ecosystem is still to adapt to it.

**Comment by de-sh** [comment]
Oh, ok, let's keep it on the backburner then :+1:

**Pull request closed without merging**
