### PR TITLE
docstring review changes

### PR DESCRIPTION
**Pull request by thrishik7**
issue: #438

### CODE REVIEW

**Comment by xadahiya** [comment]
@thrishik7 Why are several test files deleted?

**Comment by thrishik7** [comment]
@xadahiya , added required changes. Please let me know if I have to change anything

**Comment by thrishik7** [comment]
@xadahiya , I didn't change anything in those test files. Why am I getting those Assertion errors in the travis log?

**Comment by thrishik7** [comment]
@xadahiya I have made the changes. Please let me know if I have to add few more changes

**Pull request merged**
