### PR TITLE
Rectify GET on /collection endpoint

### PR DESCRIPTION
**Pull request by sameshl**
### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Description

* previously(PR #488 ) `/class` endpoint served all the members of class, now made `/collection` endpoint to serve all members of class.
* `/class` endpoint still used for adding class members.(**PUT**)
* **GET** on `/class` endpoint gives `405` status code.

### CODE REVIEW

**Comment by chrizandr** [comment]
Just check once why tests did not catch the change of serving the collection at `/class`. Add tests for that if needed.

**Comment by sameshl** [comment]
@chrizandr Conflicts have been resolved. PR is good to be merged :+1:

**Comment by priyanshunayan** [comment]
@sameshl  Please add `DroneCollection` collection in the APIDOC, it's missing.

**Comment by sameshl** [comment]
> @sameshl Please add `DroneCollection` collection in the APIDOC, it's missing.

Okay, I could do that. But I don't think that is related to this PR, could you please open an issue for the same?

**Pull request merged**
