### PR TITLE
Generic Refactoring to utilise str.format()

### LINKED ISSUE #303: Generic Refactoring
### Current Behaviour:
Some code is not readable and some optimization should be applied. For example:
* URL formatting should be using: `str.format()`: `'{}/{}/{}'.format(..., ..., ...)` or better `f'{domain}/{path}/{id}'`
* issue #301
* please @chrizandr @xadahiya add to the list
* Adding doc strings wherever missing

### Expected Behaviour:
Code should be refactored

### PR DESCRIPTION
**Pull request by de-sh**
Fixes #303 

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Description

Converted all string additions with '+' operator in repo into formatted strings (with .format()) as planned. Works(Used Pipenv).

### Test Logs

```
Creating a temporary database...
going for create doc
Classes and properties added successfully.
Setting up Hydrus utilities...
Creating utilities context...
Setup done, running tests...
..../demoapi/anotherSingleClass
{'@context': '/demoapi/contexts/anotherSingleClass.jsonld', '@id': '/demoapi/', '@type': 'anotherSingleClass', 'Prop1': 'KBFVUD'}
/demoapi/singleClass
{'@context': '/demoapi/contexts/singleClass.jsonld', '@id': '/demoapi/', '@type': 'singleClass', 'Prop1': 'UHSHQW', 'Prop2': 'P88362', 'dummyProp': '/demoapi/DcTest/840dc876-81a6-4edc-92a4-644adcb786d7', 'singleClassProp': '/demoapi/anotherSingleClass/'}
.............Creating a temporary datatbase...
Classes, Properties and Users added successfully.
Setting up Hydrus utilities...
Creating utilities context...
Setup done, running tests...
..........Creating a temporary datatbsse...
['User', 'Pet']
Pet
Classes and properties added successfully.
Setup done, running tests...
.........SELECT EXISTS (SELECT *
FROM instances
WHERE instances.id = ?) AS anon_1
.......Importing Open Api Documentation ..
......Method on path /pet/findByStatus already present !
Method on path /pet/findByTags already present !
Method on path /pet/{petId} already present !
Cannot parse path /pet/{petId} because no ref to local class provided
Cannot parse path /pet/{petId} because no ref to local class provided
Cannot parse path /store/inventory because no ref to local class provided
Cannot parse path /store/order/{orderId} because no ref to local class provided
Method on path /user/createWithArray already present !
Method on path /user/createWithList already present !
Cannot parse path /user/login because no ref to local class provided
Cannot parse path /user/logout because no ref to local class provided
Cannot parse path /user/{username} because no ref to local class provided
...
----------------------------------------------------------------------
Ran 52 tests in 1.868s

OK
```

### Changes log
- Exchanged string concatenation for str.format() expressions.
- Exchanged most old string formatting expressions (using %) with str.format() expressions.

#### Added

- String formatting using str.format function within codebase.

#### Changed

- NONE

#### Fixed

- NONE

#### Removed

- NONE

### CODE REVIEW

**Comment by de-sh** [comment]
Sorry for so many PRs. The GitHub UX is new to me and hence unintuitive. Please forgive me.

**Comment by xadahiya** [comment]
@de-sh can you please fix the conflicts? Then we can proceed with this.
Thanks 😄

**Comment by de-sh** [comment]
@xadahiya conflicts have been resolved.

**Comment by xadahiya** [comment]
Tests failing

**Comment by xadahiya** [comment]
> 
> 
> @xadahiya, what's with [hydrus/tests/test_doc_writer.py.d232acdff5bf6add5d41cf1ed0134729.py](https://github.com/xadahiya/hydrus/commit/549a1e895cdb6b7dd553432dc9cff5ea3655d997#diff-dc54223f701bcd97f64f892a053a2a2b)?
> 
> If it was generated by a pep8 code formatter, can it be deleted?

Not sure how was that created. REMOVED now

**Comment by de-sh** [comment]
DONE! Finally corrected all problems with the code. The develop branch code-base is now completely PEP8 compliant :champagne:. Happy New Year :100:  :joy:

**Pull request merged**
