### PR TITLE
Added new endpoint to Get/Delete member of a collection.

### LINKED ISSUE #553: Add support to get/update/delete members of a collection.
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

Currently, there is no API endpoint to get,update or delete members from a Collection. To delete a single object(member) from a Collection we'll have to make a POST request to `<collection_endpoint>/<collection_id>` with whole updated Collection.
### Expected Behaviour:

To make this process easier, we can add a feature or new endpoint in hydrus to delete or get a particular member from a Collection. To add a member to Collection, a PUT request can be made as usual.
### Environment:
 
* python version
* pip version
* OS details

### Do you want to work on this issue?

**Yes**

### PR DESCRIPTION
**Pull request by farazkhanfk7**
Fixes #553 
Related to #494 

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.6.0 and above.

### Description

Currently, there is no API endpoint to get, update or delete members from a Collection. To delete a single object(member) from a Collection we'll have to make a POST request to `<collection_endpoint>/<collection_id>` with updated Collection. 
I tried to create a new endpoint that takes both collection_id and member's id, so that we can delete or get a particular member from that Collection. Please let me know what should be a right approach to move forward with this. I also need some suggestions on what should be the name of these functions.

### Change logs

-  Added a new endpoint  `{api_name}/<string:path>/<uuid:collection_id_>/<uuid:id_>`
-  Added custom Exception to handle operations.

Using movie_apidoc for this example. 

**GET** :  `http://localhost:8080/serverapi/MovieCollection/26d9ae29-66af-4dc3-8214-085bfb3b9ee5`**/**`0fa1f87f-73d2-4ec4-ae9a-ecf18b2469dd`
```
{
    "@context": "http://localhost:8080/serverapi/contexts/MovieCollection.jsonld",
    "@id": "http://localhost:8080/serverapi/MovieCollection/26d9ae29-66af-4dc3-8214-085bfb3b9ee5",
    "@type": "MovieCollection",
    "members": [
        {
            "@id": "http://localhost:8080/serverapi/Movie/0fa1f87f-73d2-4ec4-ae9a-ecf18b2469dd",
            "@type": "hydra:Link"
        }
    ]
}
```

**DELETE** : `http://localhost:8080/serverapi/MovieCollection/26d9ae29-66af-4dc3-8214-085bfb3b9ee5`**/**`0fa1f87f-73d2-4ec4-ae9a-ecf18b2469dd`

```
{
    "@context": "http://www.w3.org/ns/hydra/context.jsonld",
    "@type": "Status",
    "description": "Object with ID 0fa1f87f-73d2-4ec4-ae9a-ecf18b2469dd successfully deleted from Collection with ID 26d9ae29-66af-4dc3-8214-085bfb3b9ee5",
    "statusCode": 200,
    "title": "Object successfully deleted."
}
```
To add a new member to Collection, a PUT request can be made as usual.

### CODE REVIEW

**Comment by farazkhanfk7** [comment]
Wanted to discuss this that currently, we do have an endpoint in hydrus to delete multiple objects from a Class (using int_list parameter) but not for a Collection. Now that we're thinking of a solution for deleting members from a collection, can we add such an endpoint for collections as well? So that we can delete multiple objects with a single request.

**Comment by Mec-iS** [comment]
Thanks @farazkhanfk7 for the great piece of work.

We cannot merge if we don't have at least few test cases to test the new behaviour. Please add your tests to the `tests` module.

**Comment by farazkhanfk7** [comment]
Sure @Mec-iS ! I'll add the tests, I also found possibilities for some more improvements related to same issue and that's probably some more code, which is why I was thinking of adding it as section in proposal and moving ahead with this after getting approval from mentors accordingly.

**Comment by Mec-iS** [comment]
yes please make the PR self-contained so we can merge the minimal viable solution and later improve on it

**Comment by farazkhanfk7** [comment]
Sure. I'll made the required changes and add the tests. I'm busy with my examinations at the moment but I'll make the changes asap.

**Comment by farazkhanfk7** [comment]
@Mec-iS  This is ready for review. I've added the tests. Also, there are some more improvements possible but like you suggested this is a minimum viable solution and we can move ahead with this for now.

**Review by Mec-iS — APPROVED** [review]

**Pull request merged**
