### PR TITLE
 Distinguishing missing credentials and incorrect credentials in app.py 

### LINKED ISSUE #152: Distinguishing between missing credentials and incorrect credentials in app.py
### I'm submitting a 
-  feature request.

### Current Behaviour:
failed_authentication() is called when credentials are missing as well as when credentials are incorrect. 

### Expected Behaviour:
Add a parameter `missing : bool` to `failed_authentication()` to return (when credentials are missing)
```
{
  "401": "Need credentials to authenticate."
}
```
and (when credentials are incorrect)
```
{
   "403": "Credentials were incorrect."
}
```
### Do you want to work on this issue?
Yes

### PR DESCRIPTION
**Pull request by py-ranoid**
Fixes #152

### Checklist
 Everything works and tested for Python 3.5.2 and above.

### Description
```
  b@man  ~/gitpository/hydrus   docmaster  curl -H "Authorization: Basic MTp0ZXwe" -H "Content-type: application/json" -X PUT -d '{"@type":"Drone","name":"Drone2","MaxSpeed":345}' http://localhost:8080/serverapi/DroneCollection
{
  "403": "Credentials were incorrect."
}
  b@man  ~/gitpository/hydrus   docmaster  curl -H "Content-type: application/json" -X PUT -d '{"@type":"Drone","name":"Drone2","MaxSpeed":345}' http://localhost:8080/serverapi/DroneCollection 
{
  "401": "Need credentials to authenticate."
}
  b@man  ~/gitpository/hydrus   docmaster  curl -H "Authorization: Basic MTp0ZXN0" -H "Content-type: application/json" -X PUT -d '{"@type":"Drone","name":"Drone2","MaxSpeed":345}' http://localhost:8080/serverapi/DroneCollection
{
  "message": "Object with ID 1 successfully added"
}

```

### CODE REVIEW

**Comment by alohamora** [comment]
I think we should send a `401 status code` on incorrect credentials response also, as `401` is the standard status code for missing or incorrect credentials and authentication whereas`403` status code is used when that user is not `authorised` to access that resource. Also the browser gives an authentication prompt only when a `401` is passed, so if we pass a `403` the user will not get a prompt to enter his credentials again.

**Comment by py-ranoid** [comment]
Agreed. I felt it would be useful to debug `failed_authentication` on the basis of status_code.

**Comment by xadahiya** [comment]
See #144, if it's not fixed there then collaborate with @alohamora to fix this.

**Comment by py-ranoid** [comment]
@xadahiya I've also added some documentation to `app.py` that I'd also like to merge into `develop`. 
Is this PR good to close and merge or do I revert the changes in this PR and then merge the documented `app.py` ?

**Comment by Mec-iS** [comment]
This should converge in #124

**Comment by alohamora** [comment]
Added message for incorrect credentials in #144

**Pull request closed without merging**
