### PR TITLE
Adding DELETE operation to drone collection

### PR DESCRIPTION
**Pull request by Guttz**
Fixes #

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Description
Adding DELETE to sample Drone API spec

@xadahiya was it just not necessary before or was there a specific reason to not have it?

### CODE REVIEW

**Comment by Mec-iS** [comment]
are you adding this to the resource or the collection? it is useful to delete single resources but not much deleting an entire collection

**Comment by Guttz** [comment]
It's directly on the resource, I've been using the Drone Collection for the client documentation so I'll try to maintain it updated as we move on.

**Comment by Mec-iS** [comment]
all changes to the Flock vocabulary have to be made in https://github.com/HTTP-APIs/hydra-flock-vocab the example in hydrus should be pulled from there.

**Comment by Guttz** [comment]
Ok, I'll be updating there

**Comment by xadahiya** [comment]
@Guttz this was not required for the demo so we didn't use it.

**Pull request merged**
