### PR TITLE
Changes related to demo.py

### LINKED ISSUE #176: demo.py: No module named doc
### I'm submitting a 
- [x] bug report.

### Current Behaviour:
Running `demo.py` raises `ModuleNotFoundError`

### Steps to reproduce:
Run the following commands:
```bash
$ cd hydrus
$ python demo.py
Traceback (most recent call last):
  File "hydrus/demo.py", line 12, in <module>
    from doc import doc
ModuleNotFoundError: No module named 'doc'
```

### Do you want to work on this issue?
Yes

### PR DESCRIPTION
**Pull request by IamRaviTejaG**
Fixes #176 

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Description
Fixes the `ModuleNotFoundError`.

### Test Logs
Not required.

### CODE REVIEW

**Comment by Mec-iS** [comment]
@IamRaviTejaG how did you test the feature before asking for merging? This was a quite evident bug and should have been spotted since the beginning. I don't feel really comfortable when I see evident bugs merged. Please explain how you missed this in the first place and be more attentive in the future.

**Comment by IamRaviTejaG** [comment]
@Mec-iS I'm extremely sorry for that. Since the last merge related to this was more focused on `cli.py`, I tested it and it ran fine. Also, with a discussion going on for where to place the `demo.py`, I moved it to the `hydrus` folder and missed out the `doc.py` file. I apologize again for all the inconvenience caused and would refrain from committing such blunders again.

**Comment by IamRaviTejaG** [comment]
@ashwani99 Done!

@Mec-iS All tests are running successfully, and all other files have been moved, renamed and imported properly in other parts of the codebase.

**Comment by IamRaviTejaG** [comment]
@Mec-iS Please review.

**Comment by IamRaviTejaG** [comment]
@Mec-iS @xadahiya @ashwani99 @alohamora Please review.

**Comment by xadahiya** [comment]
@IamRaviTejaG  Please resolve conflicts before merging.

**Comment by IamRaviTejaG** [comment]
@xadahiya Done! 😄

**Pull request merged**
