### PR TITLE
Hydra objects to OpenApi Objects.

### LINKED ISSUE #195: Basic Implementation Hydra ->Open Api parser
### I'm submitting a 
- [ ] bug report.
- [X] feature request.

Basic implementation of Hydra to Open Api definition , will converts most used objects of both and will generate a YAML file from Hydra Api Doc . 
### Do you want to work on this issue?
Yes !

### PR DESCRIPTION
**Pull request by vaibhavchellani**
Fixes #195 

### Checklist
- [X ] My branch is up-to-date with upstream/develop branch.
- [X ] Everything works and tested for Python 3.5.2 and above.

### Test Logs

screen shot 2018-05-18 at 11 24 16 am

#### Added

- PyYaml to generate yaml file
- Basic structure of Open Api Definition 
- Can parse classes and make them definitions in OAS
- Can parse properties and descriptions and add as child objects of definitions

### CODE REVIEW

**Comment by chrizandr** [comment]
I notice that you are trying to convert a Hydra API doc to OpenAPI, what we need however is for OpenAPI -> HydraAPI doc.
The reason we wanted a module for this is so that people who use OpenAPI, can easily use __hydrus__ without having to create separate API documentation, by directly using the parser.

**Comment by vaibhavchellani** [comment]
yes i know the requirement is for Open Api -> Hydra , but following the discussion in #149 and the reasons i mentioned in my proposal i went for Hydra->Open Api . I thought i could make sure this way that we were able to map every object correctly , now that i have looked at both the specs closely enough i think we can directly go for Open Api -> Hydra , what do you suggest ?

**Comment by xadahiya** [comment]
I think you should start working on openapi > hydra parser. If you get stuck at some point then we can figure it out along the way.

**Comment by vaibhavchellani** [comment]
okay @xadahiya sounds cool !

**Pull request closed without merging**
