### PR TITLE
FIX: incomplete contexts in hydrus demo

### LINKED ISSUE #429: demo returns incomplete contexts
### I'm submitting a 
- [X] bug report.

### Current Behaviour:
I'm exploring the hydrus demo to understand how Hydra works. From what I understand, the linked JSON-LD contexts do not provide enough information to parse a response as RDF.

Requesting the `DroneCollection` returns the following JSON-LD document:

```jsonc
// GET http://localhost:8080/serverapi/DroneCollection

{
  "@context": "/serverapi/contexts/DroneCollection.jsonld",
  "@id": "/serverapi/DroneCollection/",
  "@type": "DroneCollection",
  "members": [],
  "search": {
    "@type": "IriTemplate",
    "mapping": [
      {
        "@type": "IriTemplateMapping",
        "property": "http://auto.schema.org/speed",
        "required": false,
        "variable": "DroneState[Speed]"
      },
// ...
    ],
    "template": "/serverapi/Drone(DroneState[Speed], DroneState[Position], DroneState[Direction], DroneState[Battery], DroneState[SensorStatus], DroneState[DroneID], name, model, MaxSpeed, Sensor, pageIndex, limit, offset)",
    "variableRepresentation": "hydra:BasicRepresentation"
  },
  "totalItems": 0,
  "view": {
    "@id": "/serverapi/DroneCollection?page=1",
    "@type": "PartialCollectionView",
    "first": "/serverapi/DroneCollection?page=1",
    "last": "/serverapi/DroneCollection?page=1"
  }
}
```

However, the linked JSON-LD context does not contain mappings for all the Hydra-specific identifiers:

```jsonc
// GET http://localhost:8080/serverapi/contexts/DroneCollection.jsonld

{
  "@context": {
    "Drone": "vocab:Drone",
    "DroneCollection": "vocab:DroneCollection",
    "hydra": "http://www.w3.org/ns/hydra/core#",
    "members": "http://www.w3.org/ns/hydra/core#member",
    "vocab": "http://localhost:8080/serverapi/vocab#"
  }
}
```

Almost none of the Hydra-identifiers in the response (`search`, `IriTemplate`, `totalItems`, `first`, `last`, etc.) can be mapped to their URIs. The issue becomes obvious, when you paste the JSON-LD along with the JSON-LD context into the JSON-LD playground:

http://tinyurl.com/rrq6cc8

### Expected Behaviour:
Either the JSON-LD context maps all the identifiers to their URIs or the identifiers are prefixed with `hydra:` in the document. E.g. like this:

```jsonc
{
  "@context": "/serverapi/contexts/DroneCollection.jsonld",
  "@id": "/serverapi/DroneCollection/",
  "@type": "DroneCollection",
  "members": [],
  "hydra:search": {
    "@type": "hydra:IriTemplate",
    "hydra:mapping": [
      {
        "@type": "hydra:IriTemplateMapping",
        "hydra:property": "http://auto.schema.org/speed",
        "hydra:required": false,
        "hydra:variable": "DroneState[Speed]"
      },
// ...
    ],
    "hydra:template": "/serverapi/Drone(DroneState[Speed], DroneState[Position], DroneState[Direction], DroneState[Battery], DroneState[SensorStatus], DroneState[DroneID], name, model, MaxSpeed, Sensor, pageIndex, limit, offset)",
    "hydra:variableRepresentation": "hydra:BasicRepresentation"
  },
  "hydra:totalItems": 0,
  "hydra:view": {
    "@id": "/serverapi/DroneCollection?page=1",
    "@type": "hydra:PartialCollectionView",
    "hydra:first": "/serverapi/DroneCollection?page=1",
    "hydra:last": "/serverapi/DroneCollection?page=1"
  }
}
```

Here's the JSON-LD playground for this document: http://tinyurl.com/r2oje6q

The same applies to other responses, e.g. the `Drone` representation, which links to the same JSON-LD context as the collection leaving `MaxSpeed`, `Sensor`, `model` and `name` undefined:

```jsonc
// GET http://localhost:8080/serverapi/DroneCollection/9299bee8-bdc6-4d6f-9f48-f5884b3ef29c

{
  "@context": "/serverapi/contexts/DroneCollection.jsonld",
  "@id": "/serverapi/DroneCollection/9299bee8-bdc6-4d6f-9f48-f5884b3ef29c",
  "@type": "Drone",
  "MaxSpeed": "100",
  "Sensor": "Temperature",
  "model": "xyz",
  "name": "Drone 1"
}
```

### Steps to reproduce:
- Start the demo according to README
- Authenticate
- `GET http://localhost:8080/serverapi/DroneCollection`
- `GET http://localhost:8080/serverapi/contexts/DroneCollection.jsonld`
- Copy/paste both, document and context, into the JSON-LD playground (or click link above)

### Do you want to work on this issue?
no, I'm not familiar with python and only wanted to learn about Hydra.

### PR DESCRIPTION
**Pull request by sameshl**
Fixes #429.

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Description

* Add context to the following properties: `totalItems`, `view`, `first`, `last` by prefixing them with `hydra`.
* Regenerated the API documentation of the hydrus demo after fixing the incomplete contexts.
* Fix tests appropriately for the changes made.

NOTE: This PR complements https://github.com/HTTP-APIs/hydra-python-core/pull/34.

### CODE REVIEW

**Comment by sameshl** [comment]
@chrizandr The build is failing because the new context format has not been added to `python-hydra-core`.

**Comment by sameshl** [comment]
@xadahiya @chrizandr Could you please review this PR whenever you are free.
Thanks!

**Comment by chrizandr** [comment]
Please make sure the builds are passing.

**Comment by sameshl** [comment]
> This change should be done first in core right? The whole API Doc object is using the core library to generate contexts.

Yes @chrizandr, you are right. For that exact reason, I have complemented this PR with this  HTTP-APIs/hydra-python-core#34 in the `hydra-python-core` repo. In which I have made appropriate changes in core.

**Comment by sameshl** [comment]
@chrizandr  @xadahiya  Could you have a look at this PR?

**Comment by xadahiya** [comment]
Build is failing, can you see what's wrong?

**Comment by sameshl** [comment]
> Build is failing, can you see what's wrong?

The builds are failing because the changes I have made rely on changes in `python-hydra-core` repo. I have made those in this PR https://github.com/HTTP-APIs/hydra-python-core/pull/34.

**Comment by xadahiya** [comment]
Merged but still failing

**Comment by sameshl** [comment]
> Merged but still failing

@xadahiya I think I know why build is failing. In `requirements.txt` https://github.com/HTTP-APIs/hydrus/blob/72b4cda49ab9cfe0fb775146e8d5113f5d6869e0/requirements.txt#L14 ,
the requirement for `hydra-python-core` is specified by its `master` branch, but the merge you did for my [PR](HTTP-APIs/hydra-python-core#34) is in the `develop` branch. Thats why the changes are not reflected in the build (as the build is fetching the `python-hydra-core` from the `master` branch). 
Locally, I tried changing the requirement to `develop` branch, and the build is passing.

**Pull request merged**
