### PR TITLE
Added extensive documentation to hydrus/utils.py. 

### LINKED ISSUE #98: Extensively document the methods
### I'm submitting a 
- [v] feature request.

### Current Behaviour
Methods' docstring do not list inputs in signatures

### Expected Behaviour:
Every method should have a docstring in this format: 
```
"""
Extensive explanation of what the method does.

:param input1: description of the input1
:param input2: description of input2
:return return_type: description of returned object
"""
```

### PR DESCRIPTION
**Pull request by py-ranoid**
Partially fixes #98

Added docstrings to all functions in utils.py. 
Explained the imports too, so it's easier for beginners to understand the functions.

### CODE REVIEW

**Comment by xadahiya** [comment]
Please create the PR to develop branch. Also, submit test logs to confirm everything is working.

**Comment by py-ranoid** [comment]
How do I get the test logs ?

**Comment by Mec-iS** [comment]
@py-ranoid run the tests and everything shall be `OK`

**Comment by xadahiya** [comment]
@py-ranoid Also, sync with develop first. Type annotations are missing.

**Comment by py-ranoid** [comment]
`hydrus/tests/test_app.py` and `hydrus/tests/test_crud.py` were `OK`.
`hydrus/tests/test_auth.py` however failed.
How can I resolve this ?

```
Creating a temporary datatbsse...
Classes, Properties and Users added successfully.
Setup done, running tests...
FFFF
======================================================================
FAIL: test_Auth_DELETE (hydrus.tests.test_auth.AuthTestCase)
Test for the index.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/b/gitpository/hydrus/hydrus/tests/test_auth.py", line 105, in test_Auth_DELETE
    assert response_get.status_code != 401
AssertionError

======================================================================
FAIL: test_Auth_GET (hydrus.tests.test_auth.AuthTestCase)
Test for the index.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/b/gitpository/hydrus/hydrus/tests/test_auth.py", line 63, in test_Auth_GET
    assert response_get.status_code != 401
AssertionError

======================================================================
FAIL: test_Auth_POST (hydrus.tests.test_auth.AuthTestCase)
Test for the index.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/b/gitpository/hydrus/hydrus/tests/test_auth.py", line 77, in test_Auth_POST
    assert response_get.status_code != 401
AssertionError

======================================================================
FAIL: test_Auth_PUT (hydrus.tests.test_auth.AuthTestCase)
Test for the index.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/b/gitpository/hydrus/hydrus/tests/test_auth.py", line 91, in test_Auth_PUT
    assert response_get.status_code != 401
AssertionError

----------------------------------------------------------------------
Ran 4 tests in 0.041s

FAILED (failures=4)

```

**Comment by xadahiya** [comment]
@py-ranoid  check your repo, I guess it's outdated. We had some problem with `test_auth`  but it's fixed now. I just ran the tests and everything seems fine.

**Comment by xadahiya** [comment]
Create PR for develop instead of master

**Comment by py-ranoid** [comment]
Yeah I did that with another PR. 
Closing this one.

@Mec-iS 
Though why does the development take place on develop ?
I mean the README encourages users to checkout to develop too.
Why not just switch to master ? 
Makes it a tad bit easier

**Comment by Mec-iS** [comment]
Master is the official current release. Develop is merged only when the milestone for releasing is reached: http://nvie.com/posts/a-successful-git-branching-model/

**Pull request closed without merging**
