### PR TITLE
Fixing typo in `demo.py` file

### LINKED ISSUE #610: Typo in `demo.py` file
### I'm submitting a 
- [x] bug report.

### Current Behaviour:
While executing the [demo.py](https://github.com/HTTP-APIs/hydrus/blob/develop/examples/hydrus-demo-server/demo.py) file, it throws the following error: `from gevent.wsgi import WSGIServer
ModuleNotFoundError: No module named 'gevent.wsgi'`

### Expected Behaviour:
The server should start running

### Steps to reproduce:
Run the [demo.py](https://github.com/HTTP-APIs/hydrus/blob/develop/examples/hydrus-demo-server/demo.py) file.

### Snapshot:
image

### Environment:
 
* python version - 3.10.2
* pip version - 22.0.3
* OS details
    - Name - Microsoft Windows 11 Home Single Language
    - Version - 10.0.22000 N/A Build 22000

### Do you want to work on this issue?

Yes

### PR DESCRIPTION
**Pull request by vrutik2809**
Fixes #610 

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.6.0 and above.

### Current behaviour
There is a typo in the `demo.py` file. Due to that the following error was occurring:
image

### New expected behaviour
The typo has been removed. Now it will work completely fine.

#### Fixed 

- Typo removed

### CODE REVIEW

**Comment by Mec-iS** [comment]
please check if the same declaration is present in other parts of the codebase

**Review by Mec-iS — APPROVED** [review]

**Comment by vrutik2809** [comment]
### Another two issues found in the same file:
- No method named `insert_classes` in `doc_parse.py` module (line: 60)
- No method named `insert_properties` in `doc_parse.py` module (line: 61)

Need to remove those lines

**Comment by Mec-iS** [comment]
you should provide the changes to fix those then. Are those methods unused or they changed names? Check `hydra-python-core` repository also.

**Comment by Mec-iS** [comment]
Those methods have been removed from `hydrus/data/doc_parse.py` so `demo.py` should be updated.

**Comment by Mec-iS** [comment]
@farazkhanfk7 do you know what we use now in place of `insert_classes` to generate the class objects?

**Comment by farazkhanfk7** [comment]
In `hydrus/data/db_models.py`, there is a Resource class which is used to create a Class or Collection. It has a function `make_db_table`, which is called by another function `create_database_tables` to insert classes in the database.
https://github.com/HTTP-APIs/hydrus/blob/c6a8587c7904afe64c31f74da1f9d4edc7139ed2/hydrus/data/db_models.py#L217-L220

**Comment by vrutik2809** [comment]
Unavailable method removed from `demo.py` file

**Comment by Mec-iS** [comment]
ok. but now the demo should work by using the new methods.

**Comment by farazkhanfk7** [comment]
@vrutik2809 you can take a look at `app.py` for reference and also make sure that hydrus server is working fine after running `demo.py`.

**Comment by vrutik2809** [comment]
While running `demo.py`, it is running two times:
- First, when I run `demo.py` it's running on `http://localhost:8080/api` without going in the `if` block
image

- Second when I hit `Ctrl + c` (in order to stop the server) then it actually goes into the `if` block and starts running on `http://localhost:8080/serverapi` but it shows `404 not found`
image

I'm not able to figure out why it is happening.

While debugging it, I also observed that even if pass a different `port` or `api-name` it still listen to  `base-url & api-name` provided while making documentation using `doc.writer.HydraDoc()`. It can be verified in the above image also. Api-name in the `doc.py` (reference image attached below) is `api` but in `demo.py` it is passed as `serverapi`  then it is throwing `404` but when I fire a request on `/api` then it gives me `200` 

snap of [doc.py](https://github.com/HTTP-APIs/hydrus/blob/develop/examples/hydrus-demo-server/doc.py) :
image

**Comment by vrutik2809** [comment]
I have opened new issue ([#613](https://github.com/HTTP-APIs/hydrus/issues/613)) regarding `PORT` and `API_NAME` problem.

**Review by Mec-iS — APPROVED** [review]

**Comment by Mec-iS** [comment]
Thanks!

**Pull request merged**
