### PR TITLE
Improve readability. Add formatters

### PR DESCRIPTION
**Pull request by Mec-iS**
* Improve readability
* Add flake8
* implement `poetry`?

It is now possible to install dependencies with conflicts auto-resolving using: `pip install poetry && poetry install`

### CODE REVIEW

**Comment by sameshl** [comment]
Great work!

LGTM :+1:

**Review by sameshl — APPROVED** [review]
Nice work!
LGTM :+1:

**Review by chrizandr — APPROVED** [review]
We can merge

**Review by priyanshunayan — APPROVED** [review]
LGTM 🚀. Much needed housekeeping 😂

**Pull request merged**
