### PR TITLE
pyyaml version changed

### PR DESCRIPTION
**Pull request by newbazz**
Fixes #

### Checklist
- [ ] My branch is up-to-date with upstream/develop branch.
- [ ] Everything works and tested for Python 3.5.2 and above.

### CODE REVIEW

**Comment by newbazz** [comment]
@Mec-iS please have a look

**Comment by newbazz** [comment]
related to https://github.com/HTTP-APIs/hydrus/issues/323

**Comment by Mec-iS** [comment]
Target branch should be `develop`. Everything should be first pushed to `develop` (not `master`)

**Comment by Mec-iS** [comment]
the commit message in not meaningful enough. Please read tutorials about how to write a commit message: https://chris.beams.io/posts/git-commit/

**Comment by newbazz** [comment]
I will read them and make suitable changes as soon as possible.

**Comment by chrizandr** [comment]
Please create a new PR to develop with appropriate changes.

**Pull request closed without merging**
