### PR TITLE
Added the collections key in the context of sample apidoc

### LINKED ISSUE #502: Add missing items in the context of response
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

Some keywords that we are using in the response are not defined in the context. For eg: At the entrypoint(`/serverapi`) of the API we are using `collections` keyword in the response but `collections` is not defined in the context of the entrypoint response. 

### Expected Behaviour:

`collections` should be defined in the context of the entrypoint response.
### Steps to reproduce:

* Start the hydrus server using default arguments.
* Navigate to  "http://localhost:8080/serverapi"
* check the context and response body
### Do you want to work on this issue?

no

### PR DESCRIPTION
**Pull request by raoashish10**
Fixes #502 

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.6.0 and above.

### Description

Previous state: There was no collections keyword in the context of the sample doc.
Added the collections keyword to the context.
#### Fixed 

Fixed the missing key in the context of sample doc for the collections keyword.

### CODE REVIEW

**Comment by raoashish10** [comment]
Not completely sure if this was the fix that was needed. Please let me know if I have missed anything. @priyanshunayan

**Comment by chrizandr** [comment]
This is not related to the issue. The issue was about the context in the response returned by the server. Contexts in the API doc are different.

**Comment by raoashish10** [comment]
@chrizandr I am not able to figure out how I can configure the context of the response. Can you please provide some hints/advice about how I can do it?

**Comment by chrizandr** [comment]
hydrus responses only generate a link for the context. Accessing that link gives the context for the class/object that is generated from doc_writer in hydra-python-core repo.

**Comment by raoashish10** [comment]
@chrizandr Understood! Thank you!

**Pull request closed without merging**
