### PR TITLE
Add pyright type checker

### LINKED ISSUE #379: Find a type checker and run it with Travis
### I'm submitting a 
- feature request.

### Current Behaviour:
Type annotations with `mypy` allow the code to tell developers which type of inputs/outputs are expected but there is no tool that checks that the annotations are respected by the functions

### Expected Behaviour:
Some command-line tool should run with CI to check if types annotations are correct. See [pyre](https://pyre-check.org/docs/guided-tour.html)

### PR DESCRIPTION
**Pull request by de-sh**
Fixes #379

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Description

Python type checking done using Microsoft/pyright in travis settings. This is a npm package that checks for type issues within the repo. 
### Change logs
Added pyright by Microsoft

### CODE REVIEW

**Comment by de-sh** [comment]
Seems like there are way too many issues being pointed out by pyright :sweat_smile:

**Comment by Mec-iS** [comment]
I think `npx` needs the `PYTHONPATH` variable set to the project directory or it cannot resolve the imports:
```
14.99s$ npx pyright .
npx: installed 1 in 1.18s
No venvPath specified. Falling back on PYTHONPATH:
  No valid paths found in PYTHONPATH environment variable.
Finding source files
```
We need to find a way to tell the job's environment about the project's directory.

**Comment by de-sh** [comment]
@Mec-iS should we instead use mypy itself?

**Comment by Mec-iS** [comment]
I only pointed out some alternatives, I gave possibility to chose. Probably `mypy` command-line is fitter as involves using the same Python stack.

If you run `npx pyright .` you will check all the modules in the project, including external libraries. What we want is to check only the modules in `hydrus/` directory.

**Comment by Mec-iS** [comment]
With your latest change:
```
7.71s$ npx pyright ./hydrus/
npx: installed 1 in 1.144s
No venvPath specified, and no search paths found for configured python interpreter.
Searching for source files
Found 22 source files
./hydrus/app.py
  5:6 - error: Import 'sqlalchemy' could not be resolved
  7:6 - error: Import 'gevent.pywsgi' could not be resolved
  8:6 - error: Import 'sqlalchemy.orm' could not be resolved
  17:6 - error: Import 'hydra_python_core' could not be resolved
./hydrus/app_factory.py
  1:6 - error: Import 'flask' could not be resolved
  2:6 - error: Import 'flask_cors' could not be resolved
  3:6 - error: Import 'flask_restful' could not be resolved
./hydrus/auth.py
  3:6 - error: Import 'flask' could not be resolved
  51:34 - error: Cannot access member 'get_HTTP' on type 'Exception'
  51:54 - error: 'ignore' is not defined
  51:54 - error: Type annotation not supported for this type of expression
./hydrus/conf.py
  42:43 - error: Operator '/' not supported for types 'str' and 'str'
  45:18 - error: Cannot instantiate abstract class 'SourceFileLoader'
 'ResourceLoader.get_data' is abstract
 'ExecutionLoader.get_filename' is abstract
  45:18 - error: Argument missing for parameter 'fullname'
./hydrus/helpers.py
  3:6 - error: Import 'flask' could not be resolved
./hydrus/resources.py
  32:6 - error: Import 'flask' could not be resolved
  33:6 - error: Import 'flask_restful' could not be resolved
./hydrus/utils.py
  23:6 - error: Import 'flask' could not be resolved
  24:6 - error: Import 'flask' could not be resolved
  27:6 - error: Import 'sqlalchemy.orm' could not be resolved
  28:6 - error: Import 'sqlalchemy.orm.session' could not be resolved
  29:6 - error: Import 'hydra_python_core.doc_writer' could not be resolved
  30:6 - error: Import 'flask.app' could not be resolved
./hydrus/data/crud.py
  35:6 - error: Import 'sqlalchemy.orm' could not be resolved
  36:6 - error: Import 'sqlalchemy' could not be resolved
  37:6 - error: Import 'sqlalchemy.orm.exc' could not be resolved
  48:6 - error: Import 'sqlalchemy.orm.scoping' could not be resolved
  434:15 - error: Cannot access member 'split' on type 'List[int]'
  658:12 - error: Expression of type 'str' cannot be assigned to return type 'int'
 'Type[str]' is incompatible with 'Type[int]'
./hydrus/data/db_models.py
  3:6 - error: Import 'sqlalchemy' could not be resolved
  4:6 - error: Import 'sqlalchemy.sql' could not be resolved
  5:6 - error: Import 'sqlalchemy.ext.declarative' could not be resolved
  6:6 - error: Import 'sqlalchemy' could not be resolved
  7:6 - error: Import 'sqlalchemy.sql' could not be resolved
./hydrus/data/doc_parse.py
  2:6 - error: Import 'sqlalchemy' could not be resolved
  6:6 - error: Import 'sqlalchemy.orm.session' could not be resolved
  7:6 - error: Import 'sqlalchemy.orm' could not be resolved
./hydrus/data/user.py
  3:6 - error: Import 'sqlalchemy' could not be resolved
  4:6 - error: Import 'sqlalchemy.orm.exc' could not be resolved
  10:6 - error: Import 'sqlalchemy.orm.session' could not be resolved
  11:6 - error: Import 'werkzeug.local' could not be resolved
  82:18 - error: Cannot access member 'id' on type 'str'
./hydrus/samples/doc_writer_sample.py
  3:6 - error: Import 'hydra_python_core.doc_writer' could not be resolved
./hydrus/tests/test_app.py
  11:6 - error: Import 'hydra_python_core' could not be resolved
  13:6 - error: Import 'sqlalchemy' could not be resolved
  14:6 - error: Import 'sqlalchemy.orm' could not be resolved
  38:20 - error: Class methods should take a 'cls' parameter
  78:23 - error: Class methods should take a 'cls' parameter
  91:21 - error: Argument of type 'Optional[dict[str, Unknown]]' cannot be assigned to parameter of type 'Dict[str, Any]'
  Type 'None' cannot be assigned to type 'Dict[str, Any]'.
./hydrus/tests/test_auth.py
  8:6 - error: Import 'hydra_python_core' could not be resolved
  10:6 - error: Import 'sqlalchemy' could not be resolved
  11:6 - error: Import 'sqlalchemy.orm' could not be resolved
  25:20 - error: Class methods should take a 'cls' parameter
  73:23 - error: Class methods should take a 'cls' parameter
./hydrus/tests/test_crud.py
  5:6 - error: Import 'sqlalchemy' could not be resolved
  6:6 - error: Import 'sqlalchemy.orm' could not be resolved
  10:6 - error: Import 'hydra_python_core' could not be resolved
  38:20 - error: Class methods should take a 'cls' parameter
  68:40 - error: Argument of type 'Optional[dict[str, Unknown]]' cannot be assigned to parameter of type 'Dict[str, Any]'
  Type 'None' cannot be assigned to type 'Dict[str, Any]'.
  77:40 - error: Argument of type 'Optional[dict[str, Unknown]]' cannot be assigned to parameter of type 'Dict[str, Any]'
  Type 'None' cannot be assigned to type 'Dict[str, Any]'.
  90:21 - error: Argument of type 'Optional[dict[str, Unknown]]' cannot be assigned to parameter of type 'Dict[str, Any]'
  Type 'None' cannot be assigned to type 'Dict[str, Any]'.
  94:21 - error: Argument of type 'Optional[dict[str, Unknown]]' cannot be assigned to parameter of type 'Dict[str, str]'
  Type 'None' cannot be assigned to type 'Dict[str, str]'.
  110:21 - error: Argument of type 'Optional[dict[str, Unknown]]' cannot be assigned to parameter of type 'Dict[str, Any]'
  Type 'None' cannot be assigned to type 'Dict[str, Any]'.
  122:40 - error: Cannot access member 'get_HTTP' on type 'Exception'
  134:40 - error: Cannot access member 'get_HTTP' on type 'Exception'
  146:40 - error: Cannot access member 'get_HTTP' on type 'Exception'
  155:21 - error: Argument of type 'Optional[dict[str, Unknown]]' cannot be assigned to parameter of type 'Dict[str, Any]'
  Type 'None' cannot be assigned to type 'Dict[str, Any]'.
  163:40 - error: Cannot access member 'get_HTTP' on type 'Exception'
  172:21 - error: Argument of type 'Optional[dict[str, Unknown]]' cannot be assigned to parameter of type 'Dict[str, Any]'
  Type 'None' cannot be assigned to type 'Dict[str, Any]'.
  176:21 - error: Argument of type 'int' cannot be assigned to parameter of type 'str'
  'Type[int]' is incompatible with 'Type[str]'
  178:40 - error: Cannot access member 'get_HTTP' on type 'Exception'
  192:25 - error: Argument of type 'Optional[dict[str, Unknown]]' cannot be assigned to parameter of type 'Dict[str, Any]'
  Type 'None' cannot be assigned to type 'Dict[str, Any]'.
  194:40 - error: Cannot access member 'get_HTTP' on type 'Exception'
  205:25 - error: Argument of type 'Optional[dict[str, Unknown]]' cannot be assigned to parameter of type 'Dict[str, Any]'
  Type 'None' cannot be assigned to type 'Dict[str, Any]'.
  207:40 - error: Cannot access member 'get_HTTP' on type 'Exception'
  223:40 - error: Cannot access member 'get_HTTP' on type 'Exception'
  236:17 - error: Argument of type 'str' cannot be assigned to parameter of type 'List[int]'
  'Type[str]' is incompatible with 'Type[List[int]]'
  248:40 - error: Cannot access member 'get_HTTP' on type 'Exception'
  252:23 - error: Class methods should take a 'cls' parameter
/home/travis/build/HTTP-APIs/hydrus/hydrus/app_factory.py
  1:6 - error: Import 'flask' could not be resolved
  2:6 - error: Import 'flask_cors' could not be resolved
  3:6 - error: Import 'flask_restful' could not be resolved
/home/travis/build/HTTP-APIs/hydrus/hydrus/conf.py
  42:43 - error: Operator '/' not supported for types 'str' and 'str'
  45:18 - error: Cannot instantiate abstract class 'SourceFileLoader'
 'ResourceLoader.get_data' is abstract
 'ExecutionLoader.get_filename' is abstract
  45:18 - error: Argument missing for parameter 'fullname'
/home/travis/build/HTTP-APIs/hydrus/hydrus/data/doc_parse.py
  2:6 - error: Import 'sqlalchemy' could not be resolved
  6:6 - error: Import 'sqlalchemy.orm.session' could not be resolved
  7:6 - error: Import 'sqlalchemy.orm' could not be resolved
/home/travis/build/HTTP-APIs/hydrus/hydrus/data/db_models.py
  3:6 - error: Import 'sqlalchemy' could not be resolved
  4:6 - error: Import 'sqlalchemy.sql' could not be resolved
  5:6 - error: Import 'sqlalchemy.ext.declarative' could not be resolved
  6:6 - error: Import 'sqlalchemy' could not be resolved
  7:6 - error: Import 'sqlalchemy.sql' could not be resolved
/home/travis/build/HTTP-APIs/hydrus/hydrus/data/user.py
  3:6 - error: Import 'sqlalchemy' could not be resolved
  4:6 - error: Import 'sqlalchemy.orm.exc' could not be resolved
  10:6 - error: Import 'sqlalchemy.orm.session' could not be resolved
  11:6 - error: Import 'werkzeug.local' could not be resolved
  82:18 - error: Cannot access member 'id' on type 'str'
/home/travis/build/HTTP-APIs/hydrus/hydrus/utils.py
  23:6 - error: Import 'flask' could not be resolved
  24:6 - error: Import 'flask' could not be resolved
  27:6 - error: Import 'sqlalchemy.orm' could not be resolved
  28:6 - error: Import 'sqlalchemy.orm.session' could not be resolved
  29:6 - error: Import 'hydra_python_core.doc_writer' could not be resolved
  30:6 - error: Import 'flask.app' could not be resolved
/home/travis/build/HTTP-APIs/hydrus/hydrus/resources.py
  32:6 - error: Import 'flask' could not be resolved
  33:6 - error: Import 'flask_restful' could not be resolved
/home/travis/build/HTTP-APIs/hydrus/hydrus/auth.py
  3:6 - error: Import 'flask' could not be resolved
  51:34 - error: Cannot access member 'get_HTTP' on type 'Exception'
  51:54 - error: 'ignore' is not defined
  51:54 - error: Type annotation not supported for this type of expression
/home/travis/build/HTTP-APIs/hydrus/hydrus/data/crud.py
  35:6 - error: Import 'sqlalchemy.orm' could not be resolved
  36:6 - error: Import 'sqlalchemy' could not be resolved
  37:6 - error: Import 'sqlalchemy.orm.exc' could not be resolved
  48:6 - error: Import 'sqlalchemy.orm.scoping' could not be resolved
  434:15 - error: Cannot access member 'split' on type 'List[int]'
  658:12 - error: Expression of type 'str' cannot be assigned to return type 'int'
 'Type[str]' is incompatible with 'Type[int]'
/home/travis/build/HTTP-APIs/hydrus/hydrus/helpers.py
  3:6 - error: Import 'flask' could not be resolved
/home/travis/build/HTTP-APIs/hydrus/hydrus/samples/doc_writer_sample.py
  3:6 - error: Import 'hydra_python_core.doc_writer' could not be resolved
118 errors, 0 warnings 
Completed in 6.404sec
The command "npx pyright ./hydrus/" exited with 1.
```

**Comment by de-sh** [comment]
Yes, I am trying out a mypy implementation in local. Will make a new PR. This seems to be a dead end ☹️

**Pull request closed without merging**
