### PR TITLE
Migrate test suite from unittest to pytest

### LINKED ISSUE #460: Migrate testsuite from unittest to pytest
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

The testsuite for hydrus is written using unittest library.
### Expected Behaviour:

@xadahiya  I feel that using pytest would greatly improve the readability of the test code with its features like fixtures, parameterisation, etc. As hydrus continues to develop and we continue to refactor it, I think this is an important point we might want to consider. The only disadvantage I feel using pytest is that it is not in the standard library.
### Do you want to work on this issue?

Yes

### PR DESCRIPTION
**Pull request by sameshl**
Fixes #460 

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Description

I have migrated the test suite of hydrus from using the python standard library's `unittest` to using `pytest`. Using `pytest` would greatly improve the readability of the test code with its features like fixtures, parameterisation, etc. 
#### To run the tests, in the `/hydrus` root folder, run `pytest`.
This is a big PR so these are some points on the changes I made so it becomes easier to read through the code:
* I have structured the `/tests` directory as
```
/tests
   /functional - Functional tests which require a`Flask` instance to run.
       /test_app.py
       /test_auth.py
       /test_socket.py
   /unit - Unit tests which do not require a `Flask` instance to run an can test other features such as CRUD operations testing
       /test_crud.py
``` 
* All the required pytest fixtures have been added in `conftest.py` which reduces the clutter in the actual test files.
* Required helper functions are also added in `conftest.py`
* Some of the tests lacked good documentation as well as good variable names. I have fixed that so reading the tests becomes easier.

### CODE REVIEW

**Comment by xadahiya** [comment]
Please resolve conflicts

**Comment by sameshl** [comment]
@xadahiya I have fixed the conflicts have a look

**Comment by sameshl** [comment]
@xadahiya I have fixed all conflicts.

**Comment by xadahiya** [comment]
Looks good! @chrizandr please take a look

**Comment by sameshl** [comment]
@chrizandr Let me know if anything needs to be changed

**Comment by sameshl** [comment]
@xadahiya Are you waiting for approval from @chrizandr ? Just asked because its already been 6 days. :sweat_smile:

**Comment by sameshl** [comment]
@xadahiya, I think this PR can be merged. Is there anything else that needs to be done?
Also, I had confirmed the test suite is working correctly here https://github.com/HTTP-APIs/hydrus/issues/460#issuecomment-621293773

**Comment by xadahiya** [comment]
Merged!

**Comment by sameshl** [comment]
Great! :smiley:

**Pull request merged**
