### PR TITLE
Separated parser repo

### PR DESCRIPTION
**Pull request by ShravanDoda**
Fixes #

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Change logs
Changed setup.py
Changed requirements.txt
added the git repo for openAPIParser

### CODE REVIEW

**Comment by chrizandr** [comment]
Builds failing, please check.

**Comment by ShravanDoda** [comment]
The problem is with pip not allowing to process dependency links. In order to do so 
`python setup.py install` would have to be used instead of `pip install -e .`

**Comment by ShravanDoda** [comment]
Using setup.py causes travis ci to crash on python 3.7dev. Throws an error
`bad marshal data`

**Comment by de-sh** [comment]
@ShravanDoda you could create a new [PyPi](https://pypi.org) package and solve the issue without making any changes to the CI settings... :smile:

**Comment by Mec-iS** [comment]
Possibly the package should be downloaded from a repository in this organisation, not from PyPi. Use the `git+git://...` syntax or use `setuptools`.

**Comment by Mec-iS** [comment]
@ShravanDoda @de-sh 
Please create a new PR here: https://github.com/HTTP-APIs/hydra-openapi-parser

Try to make a joint PR so you can collaborate and merge the best work possible.

**Pull request closed without merging**
