### PR TITLE
Moved examples file into `examples` 

### LINKED ISSUE #322: Move examples file into `examples`
`petstore_openapi.yaml`, like any other examples-related data, should be in the `examples` directory.

### PR DESCRIPTION
**Pull request by knakul853**
Fixes #322 

### Checklist
 - [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Description

Moved examples file into `examples` 

### Change logs

 
moved  petstore_openapi.yaml  to 'examples'

moved doc.jsonld to 'examples'

### CODE REVIEW

**Comment by Mec-iS** [comment]
Have you checked that all the code and commands used by the examples can find properly the files in their new directory?
Also, you dont need all these commits, you can squash everything in one commit "Moving examples files"

**Comment by Mec-iS** [comment]
@vddesai1871 one file is YAML the other is JSON-LD

**Comment by vddesai1871** [comment]
Yeah, but he has renamed `doc.jsonld` to `doc.jasonld`

**Comment by Mec-iS** [comment]
Yeah that is not correct.

**Comment by knakul853** [comment]
@Mec-iS  next time i will make sure to squash everything in one commit

**Comment by knakul853** [comment]
@chrizandr  checked all the imports in all the directory everything works fine

**Comment by knakul853** [comment]
rename to ```.jsonld```

**Pull request merged**
