### PR TITLE
KeyboardInterrupt Added

### PR DESCRIPTION
**Pull request by ayushiiit**
Added keyboard interrupt using try catch so that server will stop on the interruption by keyboard. Refer issue #80 .

### CODE REVIEW

**Comment by Mec-iS** [comment]
Thanks for the PR.
Any change should be first PRed first in `develop`, `master` can only receive merge from `develop`.

**Comment by ayushiiit** [comment]
Ok Done. Thanks !

**Comment by Mec-iS** [comment]
Please confirm also that all tests pass successfully.

**Comment by Mec-iS** [comment]
Reference #83

**Comment by chrizandr** [comment]
Also to be noted that this is not really an issue. A keyboard interrupt is a way for us to stop the server. Although this is not the only way to do it. You could just use the built in kill command on the OS which would send a sigkill to the process. 

A server is supposed to continuously listen for requests and so it needs to be always running. If we actually have some other use of keyboard interrupts, then it would make sense to catch them and do some operations. However, since there is no explicit operation, not catching the exception is the same as catching it and doing nothing (which is what you did in your code)

I appreciate you trying to make changes to the server, nice job on that part. I will merge these changes still, but please make sure that you're not creating issues just for the sake of getting PRs accepted.

**Pull request merged**
