### PR TITLE
Unique constraint for member ID in collections

### LINKED ISSUE #555: Avoid insertion of duplicate members in a collection
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

Currently, a member with the same ID can be added multiple times in the same collection.
### Expected Behaviour:

Member ID in Collection database table should be unique and hydrus should raise and handle the integrity error everytime an object with existing ID is inserted in a collection. A response with 400 (Bad Request) code should be returned instead of a server error.

### Steps to reproduce:

- Make a PUT request to a Collection endpoint : `http://localhost:8080/serverapi/<collection_name>/<collection-id>`
- Insert an object again with same Object ID in JSON body using PUT request.

### Environment:
 
* python version
* pip version
* OS details

### Do you want to work on this issue?

Yes

### PR DESCRIPTION
**Pull request by farazkhanfk7**
Fixes #555

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.6.0 and above.

### Description

- Previously,  a member with the same ID can be added multiple times in the same collection.
- Member ID in Collection database table is changed to a unique key and hydrus handles the integrity error and raises InstanceExists error if an object with existing ID is inserted in a collection. A response with 400 (Bad Request) code is returned.

```
{
    "@context": "http://www.w3.org/ns/hydra/context.jsonld",
    "@type": "Error",
    "description": "Instance of type Movie with ID c1b62361-e9c6-4185-b496-b74dff4fb8a4 already exists",
    "statusCode": 400,
    "title": "Instance already exists."
}
```

### CODE REVIEW

**Comment by Mec-iS** [comment]
Please add a unit test in the proper test module. we cannot accept any change without at least one test case. Follow the current convention for other tests.

**Comment by farazkhanfk7** [comment]
Sure! I'll add the tests.

**Comment by Mec-iS** [comment]
also, it seems to me that you are working on the `title` property, the primary `uuid` is used as s primary key and in the `id_` property.

@samesh please code review

**Comment by farazkhanfk7** [comment]
Yes, because in a collection table `id_` will be generated by default and it'll serve as the primary uuid. Whereas, member(id) will be taken from `title` of supported_property but it should be unique as well(This isn't the case with a Class), so that no member can be added more than once.

**Review by sameshl — COMMENTED** [review]
Good work @farazkhanfk7, LGTM :+1:

**Review by sameshl — APPROVED** [review]

**Pull request merged**
