### PR TITLE
Added endpoint to delete multiple members from a Collection.

### LINKED ISSUE #579: Create new endpoints to delete multiple members from a Collection
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

To make it easier for a user to delete multiple members from a Collection we can add an
endpoint that would allow us to do this. Currently, we do have endpoints to insert multiple
objects or even delete multiple objects by making a single request to a Class endpoint, but
no such endpoint is there for Collections.

### Expected Behaviour:

An endpoint can be created that would allow us to make a DELETE request with
collection_id and multiple members ids in ids_list as parameter.
`<api-name>/<resource_name>/<collection-id>/delete/<ids_list> `
### Environment:
 
* python version
* pip version
* OS details

### Do you want to work on this issue?

Yes

### PR DESCRIPTION
**Pull request by farazkhanfk7**
Fixes #579 

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.6.0 and above.

### Current behaviour

Currently, we do have endpoints to insert multiple
objects or even delete multiple objects by making a single request to a Class endpoint, but
no such endpoint is there to delete multiple members from a Collection.
### New expected behaviour

Create an endpoint to make a DELETE request with
collection_id and multiple members ids in ids_list as parameter.
`<api-name>/<resource_name>/<collection-id>/delete/<ids_list>`

DELETE : 
Example endpoint : 
```
/serverapi/MovieCollection/4f61070a-f647-4a65-9b0a-cbab4bcf0510/delete/3e1462f8-93ad-4a52-a371-a6fd5724c904, 1f6f1df8-788d-430a-8398-2e3302407fc0
```

```
{
    "@context": "https://raw.githubusercontent.com/HydraCG/Specifications/master/spec/latest/core/core.jsonld",
    "@type": "Status",
    "description": "Objects with ID ['3e1462f8-93ad-4a52-a371-a6fd5724c904', '1f6f1df8-788d-430a-8398-2e3302407fc0'] successfully deleted",
    "statusCode": 200,
    "title": "Objects successfully deleted"
}
```

### CODE REVIEW

**Comment by farazkhanfk7** [comment]
This still needs tests. If everything looks okay I'll add the tests.

**Comment by Mec-iS** [comment]
please proceed adding tests

**Review by sameshl — COMMENTED** [review]
LGTM.  Great work 🚀 

Could you add some example usage of the API endpoint like how it was done in https://github.com/HTTP-APIs/hydrus/pull/493 ? 

Also, you can add relevant tests.

**Comment by farazkhanfk7** [comment]
I've added the test.

**Comment by Mec-iS** [comment]
cool, please rebase from `develop` as the directory structure is changed.

**Comment by farazkhanfk7** [comment]
rebasing done. please cross-check.

**Pull request merged**
