### PR TITLE
Move OpenAPI Parser into own repo

### LINKED ISSUE #330: Make OpenAPI parser into its own repository
The OpenAPI -> Hydra parser should be segregated into its own repository and downloaded by hydrus via `requirements.txt`. It may be also published in PyPi eventually.

### PR DESCRIPTION
**Pull request by de-sh**
Fixes #330 

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Description

Moved contents of hydrus/parser to new [repo](https://github.com/HTTP-APIs/hydra-openapi-parser/pull/2) along with associated tests. Also changed dependencies in few files and CI to mirror these changes.

### Change logs
Moved hydrus/parser to new repo, associated tests and also changed imports within program files of hydrus.

*NOTE*: Tests might not work, will make PRs to correct them.

### CODE REVIEW

**Comment by de-sh** [comment]
@xadahiya are the files hydrus/samples only required by the OAPI parser?

**Comment by xadahiya** [comment]
@de-sh I wouldn't say required. Files with `open-api` in their names serve as an example of what open-api-parse does.

**Comment by Mec-iS** [comment]
Please refer to the new repo as ported out in https://github.com/HTTP-APIs/hydra-openapi-parser

**Comment by Mec-iS** [comment]
solved by #354

**Pull request closed without merging**
