### PR TITLE
Version bump to 0.3.0

### PR DESCRIPTION
**Pull request by xadahiya**
Fixes #

### Checklist
- [ ] My branch is up-to-date with upstream/develop branch.
- [ ] Everything works and tested for Python 3.5.2 and above.

### CODE REVIEW

**Comment by vddesai1871** [comment]
Do not merge, why none of this merge PRs have the changes I made in this commit https://github.com/HTTP-APIs/hydrus/pull/419/commits/d5d908fc4b45a904086327b29cd5addceb26bdbc

or am I missing something?

**Comment by chrizandr** [comment]
It is there in the list of commits @vddesai1871

**Comment by xadahiya** [comment]
@vddesai1871 `requirements.txt` in develop branch uses `hydra-python-core@develop`. See https://github.com/HTTP-APIs/hydrus/blob/develop/requirements.txt . Not sure why

**Comment by xadahiya** [comment]
Also, @chrizandr  why are there so many changes even though we just synced?

**Comment by vddesai1871** [comment]
>It is there in the list of commits @vddesai1871

Yeah but while using view file option in file changes I can't see the effect of the commit, the file still has develop branch of hydra-python-core.

**Comment by chrizandr** [comment]
> Also, @chrizandr why are there so many changes even though we just synced?

The commits were squashed and merged. They are not there individually. I suggest we makethe version bump directly in master instead?

**Comment by xadahiya** [comment]
@chrizandr  Even if the commits were squashed then the number of commits will vary i.e (develop will be behind by a number of commits) but not in file contents.

**Comment by Mec-iS** [comment]
Also remember to build the version package and publish it on PyPI

**Comment by xadahiya** [comment]
@vddesai1871 Your change was merged here https://github.com/HTTP-APIs/hydrus/pull/415/files#diff-b4ef698db8ca845e5845c4618278f29aL29

**Comment by vddesai1871** [comment]
>Not sure why
In commit history of that file, it shows it was changed when I resolved merge conflicts, while I haven't touched that file while resolving conflicts as there were no conflicts in that file. It's scary.

**Comment by xadahiya** [comment]
Let's revert the last PR and do it again.

**Comment by chrizandr** [comment]
I think I found the issue. 
Basically when Vishal was doing the changes to sync develop with master, he undid his commit.

https://github.com/HTTP-APIs/hydrus/commit/8607ec6c8f8bafccd89c64b4df9d8d099f1696e9#diff-b4ef698db8ca845e5845c4618278f29a

Maybe this was because of his fork not being upto date. Those changes were pushed directly to develop instead of doing a PR so we never noticed the changes either. We might have to revert and resync everything.

**Pull request merged**
